# Generated by Django 4.2.16 on 2025-09-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('verified_reports', models.PositiveIntegerField(default=0)),
                ('pending_reports', models.PositiveIntegerField(default=0)),
                ('rejected_reports', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('high_severity_reports', models.PositiveIntegerField(default=0)),
                ('active_hotspots', models.PositiveIntegerField(default=0)),
                ('social_media_mentions', models.PositiveIntegerField(default=0)),
                ('trending_keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RegionalStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('north_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('south_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('east_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('west_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('total_reports_month', models.PositiveIntegerField(default=0)),
                ('critical_reports_month', models.PositiveIntegerField(default=0)),
                ('active_users_month', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'regional_statistics',
                'ordering': ['state', 'region_name'],
            },
        ),
        migrations.CreateModel(
            name='TrendingKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('mention_count', models.PositiveIntegerField(default=0)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_hazard_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.hazardtype')),
            ],
            options={
                'db_table': 'trending_keywords',
                'ordering': ['-mention_count'],
                'unique_together': {('keyword', 'date')},
            },
        ),
    ]
