# Generated by Django 4.2.16 on 2025-09-13 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('api_endpoint', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'social_media_platforms',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Post ID from the social media platform', max_length=100)),
                ('content', models.TextField()),
                ('author_username', models.CharField(max_length=100)),
                ('author_followers', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('keywords', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_verified_source', models.BooleanField(default=False)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('posted_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('detected_hazard_types', models.ManyToManyField(blank=True, related_name='social_media_posts', to='reports.hazardtype')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social_media.socialmediaplatform')),
            ],
            options={
                'db_table': 'social_media_posts',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('spike', 'Mention Spike'), ('sentiment', 'Negative Sentiment'), ('location', 'Location-based Alert'), ('verification', 'Needs Verification')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('severity_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('hazard_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.hazardtype')),
                ('related_posts', models.ManyToManyField(related_name='alerts', to='social_media.socialmediapost')),
            ],
            options={
                'db_table': 'social_media_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('variations', models.JSONField(default=list, help_text='Alternative spellings and translations')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher numbers = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_hazard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_keywords', to='reports.hazardtype')),
            ],
            options={
                'db_table': 'monitoring_keywords',
                'ordering': ['-priority', 'keyword'],
            },
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['posted_at', 'relevance_score'], name='social_medi_posted__b09ced_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['latitude', 'longitude'], name='social_medi_latitud_f5a2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['sentiment', 'confidence_score'], name='social_medi_sentime_a0e83c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediapost',
            unique_together={('platform', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='socialmediaalert',
            index=models.Index(fields=['alert_type', 'is_active'], name='social_medi_alert_t_61a2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaalert',
            index=models.Index(fields=['severity_score', 'created_at'], name='social_medi_severit_39386a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringkeyword',
            unique_together={('keyword', 'language')},
        ),
    ]
